"""Add error column to videos table

Revision ID: 8607779f399f
Revises: 2ffe8ef1f36b
Create Date: 2026-05-21 20:49:15.926159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8607779f399f'
down_revision: Union[str, Sequence[str], None] = '2ffe8ef1f36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'error')
    # ### end Alembic commands ###
